# Generated by Django 5.1.1 on 2024-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
